name: chatapp
description: Flutter simple chat app with Firestore backend by Flutter Warsaw.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.0
  firebase_analytics: ^1.0.4
  cloud_firestore: ^0.9.5
  scoped_model: ^1.0.1
  uuid: ^2.0.0
  shared_preferences: 0.5.1+1
  cached_network_image: 0.7.0
  intl:
  font_awesome_flutter:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatar_placeholder.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
